EDA function for LotFrontage, LotArea, MasVnrArea, BsmtFinSF1, BsmtFi…
srwight/revIowaHousing pull request #35
Opened 2020-01-04 00:17 UTC by kylestormcloud

…nSF2

Some of the features, particularly BsmtFinSF2 and surprisingly LotArea, have weak correlation with SalePrice. For now, I have not deleted any features. This function takes in the complete housing dataframe as a parameter and return a dataframe that contains only my features.

2020-01-04 04:35 UTC, srwight requested changes
Can you pull the visualizations, and just do the feature engineering? Instead, hold on to your visualizations, and use them when we talk / build a presentation.

2020-01-04 04:38 UTC, srwight commented on clou.py
> +
for 13-16:
Have you considered:
myFeatures = ['SalePrice','BsmtFinSF2', 'BsmtFinSF1', 'MasVnrArea', 'LotArea', 'LotFrontage']
myDF = dataframe[myfeatures]
?
Might be a smidge faster.

2020-01-05 00:31 UTC, Hwailaluta requested changes
1. Return your features. 2. The changes you made in the data before were left out on your second version. 3. Please put imports outside of the function. 4. Be sure to fillna and don't dropna as we need to keep all the rows of data in for now.

One last thing: since you were absent the day we assigned these features, I also did EDA on your features. It doesn't matter now as I can change my code later.

Thank you :)

2020-01-05 02:51 UTC, srwight commented
Kyle, when you were out on 12/24 was when we initially assigned these. Since you were out, Desmond picked up yours. We now have two copies of those variables. We should figure out how to handle that.

2020-01-05 23:14 UTC, srwight commented
Superseded and outdated. Closing.

2020-01-05 23:14 UTC, closed without merging