Feature Engineering
srwight/revIowaHousing pull request #45
Opened 2020-01-05 00:13 UTC by Hwailaluta

My variables were: exterior1st, exterior2nd, roofmatl, lotarea, lotfrontage, masvnrarea, BsmtFinSF1, BsmtFinSF2, and masvnrtype.

2020-01-05 02:49 UTC, srwight reviewed
Waiting to approve until we hear back from Kyle about duplicated effort

2020-01-05 02:59 UTC, Hwailaluta commented on hend.py
> +    #I replaced outliers with the mean.
*Clipped, not mean.

2020-01-05 04:25 UTC, srwight commented on hend.py
> +
get_dummies doesn't put them into the dataframe. It returns them. You'll need to capture them in a variable and add them back to your frame.

2020-01-05 04:26 UTC, srwight commented on hend.py
> +
Your return df will have other columns, too, which will be the dummies you made up above.

2020-01-05 04:27 UTC, srwight commented on hend.py
> +    #df.drop(['BsmtFinSF1'], axis = 1, inplace=True)
Is this a copy/paste error? you have the same line twice, which will throw an error when the second line can't find the column.

2020-01-05 04:31 UTC, srwight commented on hend.py
> +    df['LotFrontage'].clip(0,((Q3 + 1.5 * IQR))
You have a hanging paren '(' after clip that isn't resolved. It looks like your goal is to clip the data to either zero or the 3rd quartile plus 1.5 IQR's, right? That looks good. But you might want to drop one of the '(' before Q3. I think that will solve your problem.

2020-01-05 04:31 UTC, srwight commented on hend.py
> +    df['MasVnrArea'].clip(0,((Q3 + 1.5 * IQR))
Same issue as above

2020-01-05 04:33 UTC, srwight requested changes
See comments within - you have some syntax issues, and your feature variables are not getting captured.

2020-01-05 04:33 UTC, srwight commented on hend.py
> +    print(feature_extract(df))
you still had 'engineer()' here. I swapped it out.

2020-01-06 17:07 UTC, srwight approved these changes
Yup

2020-01-06 18:28 UTC, disassembledd approved these changes

2020-01-06 18:28 UTC, merged